name: Pack client and server, publish as GitHub Release

on: [push, workflow_dispatch]

jobs:
  build:
    name: Pack distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pybunch
      run: >-
        python3 -m
        pip install
        pybunch
        --user
    - name: Create dist folder
      run: mkdir dist
    - name: Pack client
      run: python3 -m pybunch -r . -e client.jebsync -o dist/JEBSync.py
    - name: Pack server
      run: python3 -m pybunch -r . -e server.__main__ -o dist/server.py
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: packed-python-distribution
        path: dist/

  github-release:
    name: >-
      Publish the Packed Python 🐍 distribution 📦 as GitHub Release
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: packed-python-distribution
        path: dist/
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
